# Generated by Django 5.2.1 on 2025-05-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('journey', 'cargo', 'seat')},
        ),
    ]
